### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by wdaniel526** [Phineas05/discord-rich-presence-plex#10]
![discord_2018-09-12_18-12-39](https://user-images.githubusercontent.com/1734051/45461531-659fa880-b6b8-11e8-84f6-223c650b6951.png)
Maybe when content is paused change to this instead of nothing
![paused2](https://user-images.githubusercontent.com/1734051/45461545-7bad6900-b6b8-11e8-9a2a-9f3dc360dd37.png)

Maybe move the Discord app id from this super().__init__("413407336082833418", self) to the plexConfig line. Making is easier for users to update their script while using custom rich presence apps

**Comment by Phineas05** [comment]
The first suggestion can't be implemented due to Discord limitations. That line automatically displays the time elapsed since the timestamp passed in the rich presence data and cannot be set to anything else. I prefer not to add it to the other two lines but in the future I might modify the script to allow users to define their own formatting for those lines.

I've added `clientID` as an optional keyword parameter for the `plexConfig` class constructor so that it can be passed while initialising the class in the `plexConfigs` list.
