### ISSUE TITLE
Time left instead of time elapsed?

### ISSUE THREAD

**Issue by FortKnox1337** [Phineas05/discord-rich-presence-plex#13]
When playing a title through Plex it just shows the time elapsed. Is there a way of having it so it shows the full duration of the video?

For instance if it's a 45min video and you are 25 seconds in it would show as

00:25 / 45:00 (elapsed or other word here)

or have it show time remaining instead like a countdown.

44:35 left.

It's just a suggestion but it might be better this way as I've had friends message me how long I've got left on something I'm watching and this way they can just see it on the rich presence info,

**Comment by Phineas05** [comment]
I've added a `timeRemaining` property to the `plexConfig` class on line 17. Set this to `True` to display time remaining instead of time elapsed.

> For instance if it's a 45min video and you are 25 seconds in it would show as
>
> 00:25 / 45:00 (elapsed or other word here)

It will be displayed this way when the media is paused. The rich presence only updates every few seconds except for the time elapsed/remaining field which uses a timestamp and updates client-side, so it will show the total time along with the time elapsed/remaining field below it while media is playing.

**Comment by FortKnox1337** [comment]
That was quick! Thanks. Works a charm! 👍
